package Convertisseur;

/**
* Convertisseur/EuroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, 4 March 2025 15:30:58 o'clock WAT
*/

public final class EuroHolder implements org.omg.CORBA.portable.Streamable
{
  public Convertisseur.Euro value = null;

  public EuroHolder ()
  {
  }

  public EuroHolder (Convertisseur.Euro initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Convertisseur.EuroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Convertisseur.EuroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Convertisseur.EuroHelper.type ();
  }

}
