package Convertisseur;


/**
* Convertisseur/Euro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, 4 March 2025 15:30:58 o'clock WAT
*/

public interface Euro extends EuroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Euro
