package Convertisseur;


/**
* Convertisseur/EuroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, 4 March 2025 15:30:58 o'clock WAT
*/

abstract public class EuroHelper
{
  private static String  _id = "IDL:Convertisseur/Euro:1.0";

  public static void insert (org.omg.CORBA.Any a, Convertisseur.Euro that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Convertisseur.Euro extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Convertisseur.EuroHelper.id (), "Euro");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Convertisseur.Euro read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EuroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Convertisseur.Euro value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Convertisseur.Euro narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Convertisseur.Euro)
      return (Convertisseur.Euro)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Convertisseur._EuroStub stub = new Convertisseur._EuroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Convertisseur.Euro unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Convertisseur.Euro)
      return (Convertisseur.Euro)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Convertisseur._EuroStub stub = new Convertisseur._EuroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
