package Convertisseur;


/**
* Convertisseur/EuroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, 4 March 2025 15:30:58 o'clock WAT
*/

public abstract class EuroPOA extends org.omg.PortableServer.Servant
 implements Convertisseur.EuroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("toDollar", new java.lang.Integer (0));
    _methods.put ("toPound", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Convertisseur/Euro/toDollar
       {
         float amount = in.read_float ();
         float $result = (float)0;
         $result = this.toDollar (amount);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // Convertisseur/Euro/toPound
       {
         float amount = in.read_float ();
         float $result = (float)0;
         $result = this.toPound (amount);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Convertisseur/Euro:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Euro _this() 
  {
    return EuroHelper.narrow(
    super._this_object());
  }

  public Euro _this(org.omg.CORBA.ORB orb) 
  {
    return EuroHelper.narrow(
    super._this_object(orb));
  }


} // class EuroPOA
