package Convertisseur;


/**
* Convertisseur/EuroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, 4 March 2025 15:30:58 o'clock WAT
*/

public interface EuroOperations 
{
  float toDollar (float amount);
  float toPound (float amount);
} // interface EuroOperations
