package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, 4 March 2025 15:20:08 o'clock WAT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
